#!/bin/sh
# Script genere automatiquement a partir de subgms
# reserve 18Go de memoire \#SBATCH --mem=18000
#$ -N Antr_IC26_GG
#
#SBATCH --mem=18000
#$ -cwd
#$ -S /bin/sh
 hhomedir=`pwd`
 nnode=`hostname`
echo "Variables"
echo "Running on        : $nnode  "
echo "targetdir         : $hhomedir "
echo "TMPDIR            : $TMPDIR"
echo "I am in           : $PWD"

# source /usr/share/Modules/init/sh

if [ -s Antr_IC26_GG.xmo ] ; then
 set  echo
   cp Antr_IC26_GG.xmo Antr_IC26_GG.xmo~
 unset  echo
fi
if [ -s Antr_IC26_GG.log ] ; then
 set  echo
   cp Antr_IC26_GG.log Antr_IC26_GG.log~
 unset  echo
fi

set echo
#time (/share/programs/GAMESS/rungms   Antr_IC26_GG xmvb 1  > Antr_IC26_GG.log)
#time (/home/humbel/fuming/softwares/gamess/2020-R2//rungms/rungms          Antr_IC26_GG xmvb 1  > Antr_IC26_GG.log)
time (/home/humbel/fuming/softwares/gamess/2020-R2//rungms        Antr_IC26_GG xmvb 1  > Antr_IC26_GG.log)
#time (rungms_                     Antr_IC26_GG xmvb 1  > Antr_IC26_GG.log)
# On doit rappatrier à la main le .xmo .gus et les wfn (si necessaire)
#cp  $TMPDIR/*.wfn  $HOMEDIR/
#cp  $TMPDIR/Antr_IC26_GG.gus  $HOMEDIR/
cp  $TMPDIR/Antr_IC26_GG.xmo  $HOMEDIR/
if [ -s Antr_IC26_GG.wfn ] ; then
 set  echo
cp  $TMPDIR/Antr_IC26_GG.wfn  $HOMEDIR/
 unset  echo
fi
unset echo
