#!/bin/sh
# Script genere automatiquement a partir de subgms
# reserve 18Go de memoire \#SBATCH --mem=18000
#$ -N H2_CAS
#
#SBATCH --mem=18000
#$ -cwd
#$ -S /bin/sh
 hhomedir=`pwd`
 nnode=`hostname`
echo "Variables"
echo "Running on        : $nnode  "
echo "targetdir         : $hhomedir "
echo "TMPDIR            : $TMPDIR"
echo "I am in           : $PWD"

# source /usr/share/Modules/init/sh

if [ -s H2_CAS.xmo ] ; then
 set  echo
   cp H2_CAS.xmo H2_CAS.xmo~
 unset  echo
fi
if [ -s H2_CAS.log ] ; then
 set  echo
   cp H2_CAS.log H2_CAS.log~
 unset  echo
fi

set echo
#time (/share/programs/GAMESS/rungms   H2_CAS xmvb 1  > H2_CAS.log)
#time (/home/humbel/fuming/softwares/gamess/2020-R2//rungms/rungms          H2_CAS xmvb 1  > H2_CAS.log)
time (/home/humbel/fuming/softwares/gamess/2020-R2//rungms        H2_CAS xmvb 1  > H2_CAS.log)
#time (rungms_                     H2_CAS xmvb 1  > H2_CAS.log)
# On doit rappatrier à la main le .xmo .gus et les wfn (si necessaire)
#cp  $TMPDIR/*.wfn  $HOMEDIR/
#cp  $TMPDIR/H2_CAS.gus  $HOMEDIR/
cp  $TMPDIR/H2_CAS.xmo  $HOMEDIR/
if [ -s H2_CAS.wfn ] ; then
 set  echo
cp  $TMPDIR/H2_CAS.wfn  $HOMEDIR/
 unset  echo
fi
unset echo
